name: fasta_filter
owner: bvalot
description: Contains a tool suite of fasta/fastq manipulation
homepage_url: https://github.com/bvalot/galaxy
long_description: |
    Filter fasta file by accession or position, subsampled fastq files
remote_repository_url: https://github.com/bvalot/galaxy
categories:
- Sequence Analysis