name: in_sillico_pcr
owner: bvalot
description: Contains tools to performed PCR and qPCR in sillico analysis
homepage_url: https://github.com/bvalot/galaxy
long_description: |
    Using known primers, you can performed in sillico PCR and qPCR analysis
remote_repository_url: https://github.com/bvalot/galaxy
categories:
- Sequence Analysis